### ISSUE TITLE
JSONDecodeError...

### ISSUE THREAD

**Issue by jjy0328** [LearningnRunning/NaverTrans#2]
`cnt = 0
for i in check:
  text = navertrans.translate(i, src_lan="ja", tar_lan="ko")
  cnt += 1
  print(cnt, text)`
  
Simply translating the list resulted in a JSONDecodeError. 
I'm using navertrans version 0.0.5 and the error is 443 and I don't know why...
Is it my fault? Or did I find a bug?

The sentence in error:
`'第一印象は「色薄っ！」 web画像で見た印象よりも、だいぶ白っぽい感じでした。黄みは確かにないのですが…こんな白くて大丈夫なのかな？ですが実際に使ってみると、その心配は吹っ飛びました。これ、ブルベの影色にめちゃ良い！どこに載せたか自分でも分かんなくなるくらい、違和感なく影として馴染みます。でも薄いとか存在感がないとかいう訳ではなく、影はしっかり作られ、立体感がばっちり出ている！不自然さなくハッキリと顔の印影が際立つので、鼻周りの立体感を出すのに特にオススメです。粉質がサラサラすぎて粒子が細かく、大きいブラシで取るとめちゃめちゃ粉が舞い飛びますｗ笑っちゃうくらいブワァー！って舞い散る。色塗った感を出さずに影感を出すためには、このくらい粒子を細かくしてふんわりと載せないとなのでしょうね。大容量サイズで買いやすいお値段とコスパも良く、3色あるので使い分けが出来るのも高評価。とても気に入りました。マイナスポイントは、粉が舞いすぎるところｗぜひリピしたいアイテム。'`

The error message is as follows:
`JSONDecodeError                           Traceback (most recent call last)
Cell In[24], line 2
      1 tmp = '第一印象は「色薄っ！」 web画像で見た印象よりも、だいぶ白っぽい感じでした。黄みは確かにないのですが…こんな白くて大丈夫なのかな？ですが実際に使ってみると、その心配は吹っ飛びました。これ、ブルベの影色にめちゃ良い！どこに載せたか自分でも分かんなくなるくらい、違和感なく影として馴染みます。でも薄いとか存在感がないとかいう訳ではなく、影はしっかり作られ、立体感がばっちり出ている！不自然さなくハッキリと顔の印影が際立つので、鼻周りの立体感を出すのに特にオススメです。粉質がサラサラすぎて粒子が細かく、大きいブラシで取るとめちゃめちゃ粉が舞い飛びますｗ笑っちゃうくらいブワァー！って舞い散る。色塗った感を出さずに影感を出すためには、このくらい粒子を細かくしてふんわりと載せないとなのでしょうね。大容量サイズで買いやすいお値段とコスパも良く、3色あるので使い分けが出来るのも高評価。とても気に入りました。マイナスポイントは、粉が舞いすぎるところｗぜひリピしたいアイテム。'
----> 2 text = navertrans.translate(tmp, src_lan="ja", tar_lan="ko")
      3 print(text) 

File [~/Desktop/Elinha/amazon_review/ar-venv/lib/python3.9/site-packages/navertrans/navertrans.py:117](https://file+.vscode-resource.vscode-cdn.net/Users/jjy/Desktop/tmp/~/Desktop/Elinha/amazon_review/ar-venv/lib/python3.9/site-packages/navertrans/navertrans.py:117), in translate(src_txt, src_lan, tar_lan)
    115 else:
    116     start_time = time.time()
--> 117     r = get_response(read_token(), src_txt, src_lan, tar_lan)
    118     passed_time = time.time() - start_time
    120     data = json.loads(r.text)

File [~/Desktop/Elinha/amazon_review/ar-venv/lib/python3.9/site-packages/navertrans/navertrans.py:58](https://file+.vscode-resource.vscode-cdn.net/Users/jjy/Desktop/tmp/~/Desktop/Elinha/amazon_review/ar-venv/lib/python3.9/site-packages/navertrans/navertrans.py:58), in get_response(TOKEN, text, src_lan, tar_lan)
     52 headers = {
     53     'user-agent': 'Mozilla[/5.0](https://file+.vscode-resource.vscode-cdn.net/5.0) (Windows NT 10.0; Win64; x64) AppleWebKit[/537.36](https://file+.vscode-resource.vscode-cdn.net/537.36) (KHTML, like Gecko) Chrome[/57.0.2987.133](https://file+.vscode-resource.vscode-cdn.net/57.0.2987.133) Safari[/537.36](https://file+.vscode-resource.vscode-cdn.net/537.36)',
     54     'referer': 'https://search.naver.com/',
     55 }
     57 r = _agent.get(base_url, params=payload, headers=headers)
---> 58 data = json.loads(r.text)
     60 if 'error' in data['message'] :
     61     r = get_response(update_token(_agent), text, src_lan, tar_lan)

File [/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py:346](https://file+.vscode-resource.vscode-cdn.net/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py:346), in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
...
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by LearningnRunning** [comment]
Thanks for finding the bug, I realised that different languages have different markings for periods.
I ended up fixing two defects.

1. Fix prompting to include text if input text is "" empty or contains only escape characters like \n
2. Fix prompting to edit to the correct language code when a non-supported language code is entered.
3. Apply separate language separators

|language|language code|period separator|
|-------|--------|----------|
|Russian | 'ru'|.|
|Portuguese | 'pt'|.|
|Japanese | 'ja'|。|
|Italian | 'it'|.|
|Vietnamese | 'vi'|.|
|Thai | 'th'|ครับ|
|Spanish | 'es'|.|
|French | 'fr'|.|
|Hindi | 'hi'|.|
|German | 'de'|.|
|Simplified Chinese | 'zh-CN' (中文 (简体))|。|
|Traditional Chinese | 'zh-TW' (中文 (繁體))|。|


I'm currently on version 0.0.7, please update.
```
pip install --upgrade navertrans
```
